config/routes.rb
Rails.application.routes.draw do
  resources :wikis
  resources :charges, only: [:new, :create]
  resources :downgrade, only: [:new, :create]
  post 'downgrade/create'

  devise_for :users do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki

 def self.update_collaborators(collaborator_string)
     return Collaborator.none if collaborator_string.blank?
     collaborator_string.split(",").map do |collaborator|
         Collaborator.find_or_create_by(email: collaborator.strip)
     end
 end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :wikis, dependent: :destroy

   after_initialize :initialize_role

   enum role: [:guest, :member, :admin]

   private

   def initialize_role
     self.role ||= :guest
   end
 end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  

  after_initialize :initialize_role

  private

  def initialize_role
    self.private = false if self.private.nil?

     end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
           key: "#{ Rails.configuration.stripe[:publishable_key] }",
           description: "Blocipedia Premium Subscription",
           amount: 15_00
       }
end

  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => 15_00,
      :description => 'Blocipedia Premium Subscription',
      :currency    => 'usd'
    )

    current_user.update_attribute(:role, 1)

    flash[:notice] = "Thank you for your Premium Subscription."
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController


  before_action :set_wiki

  def index
    @collaborators = @wiki.collaborators
    @users = User.all
  end

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = @wiki.collaborators.new(:user_id => params[:user_id])

    if @collaborator.save
       flash[:notice] = "Collaborator was added to this wiki."
       redirect_to @wiki
    else
       flash[:error] = "There was an error adding the collaborator.  Please try again."
       render :back
    end
  end

  def destroy
    @collaborator = @wiki.collaborators.find(params[:id])

    if @collaborator.destroy
       flash[:notice] = "Collaborator was removed from this wiki."
       redirect_to @wiki
    else
       flash[:error] = "Collaborator could not be removed. Please try again."
       render :index
    end
  end

  def set_wiki
     @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    redirect_to_root_path
  end
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
    def new
    end

    def create
        current_user.update_attribute(:role, 0)
        wikis = Wiki.all
        wikis.each do |wiki|
        	if wiki.user.id == current_user.id
        		wiki.update_attribute(:private, false)
        	end
        end

        flash[:notice] = "You have successfully downgraded your account."

        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @private_wikis = WikiPolicy::Scope.new(@user, Wiki).my_private_wiki
    @public_wikis = WikiPolicy::Scope.new(@user, Wiki).my_public_wiki
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "Your Premium status has been changed to Guest status. All of your Wikis are now public."
      redirect_to root_path
    else
      flash[:error] = "An error has occurred when attempting to convert your account."
      redirect_to root_path
    end
  end

   private

   def user_params
     params.require(:user).permit(:name, :email, :role)
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    unless (@wiki.private == false) || (@wiki.private == nil) || current_user.member? || current_user.admin?
      flash[:alert] = "You must be a premium user to view private topics."
        if current_user
          redirect_to new_charge_path
        else
          redirect_to new_user_registration_path
         end
     end
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Your wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
        @wiki.assign_attributes(wiki_params)
        authorize @wiki

        if @wiki.save && (@wiki.user == current_user || current_user.admin?)
          @wiki.collaborators = Collaborator.update_collaborators(params[:wiki][:collaborators])
          flash[:notice] = "\"#{@wiki.title}\" was updated successfully."
          redirect_to @wiki
        elsif @wiki.save
          flash[:notice] = "Wiki was updated successfully."
          redirect_to @wiki
        else
          flash.now[:alert] = "There was an error saving the wiki. Please try again."
          render :edit
     end
   end

   def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki

     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
   end

   private

     def wiki_params
       params.require(:wiki).permit(:title, :body, :private)
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def user_is_authorized_to_create?
        current_user && (current_user.admin? || current_user.member?)
    end

    def user_is_authorized_to_update?
            current_user
    end

    def user_is_authorized_to_delete?
        current_user && (current_user == @wiki.user || current_user.admin?)
    end

    def markdown(text)
        extensions = [:tables, :fenced_code_blocks, :autolink, :strikethrough, :underline, :highlight, :quote, :footnotes]
        Markdown.new(text, *extensions).to_html.html_safe
    end
  end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$15.00</strong>and now enjoy all the priveledges of a Premium membership!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <h4>Upgrade to a Premium Membership</h4>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/_form.html.erb
<%= f.label :collaborators %>
<%= f.text_field :collaborators,
        class: 'form-control',
        placeholder: "Enter collaborator emails (separated by commas)",
        value: collaborators.map(&:email).join(', ') %>

app/views/collaborators/index.html.erb
<h3>Add Collaborators</h3>
<div class='pull-right'><h4><%= link_to "Back To: Edit Wiki", edit_wiki_path(@wiki) %></h4>
</div>
  <table>
    <tr><th>User Name</th><th>User Email</th><th>Collaborator?</th></tr>
  <% @users.each do |user| %>
    <% if user.id != @wiki.user_id %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <% if @wiki.users.include?(user) %>
            <%= link_to "Remove", wiki_collaborator_path(@wiki, @wiki.collaborator_for(user)), method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to "Add", wiki_collaborators_path(@wiki.id, user_id: user.id), method: :post, class: 'btn btn-success' %>
          <% end %>
        </td>
      </tr>
    <% end %> <!-- end of if statement -->
  <% end %> <!-- end of @users.each loop -->
  </table>
</div>

app/views/downgrade/new.html.erb
<h4>Would you like to downgrade your account back to standard?</h4>
<p> Your private wikis will become public.</p>
<%= link_to "Downgrade Your Account", downgrade_create_path, method: :create, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  'https://js.stripe.com/v2/' %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name=> 'stripe-key', :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>

      <div class="pull-right-user-info">
        <% if user_signed_in? %>
          <div class="pull-right">
            <ul class="nav nav-tabs", style="border-bottom:0px;">
              <li class="username">Signed in as: <strong><%= current_user.email %></strong></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <% if current_user.guest? %>
                <li><%= link_to 'Upgrade to Premium', new_charge_path, :class => 'navbar-link' %></li>
              <% elsif current_user.member? %>
                <li><%= link_to 'Downgrade Your Account', new_downgrade_path, :class => 'navbar-link' %></li>
              <% end %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            </ul>
          </div>
        <% else %>
          <div class="pull-right">
            <ul class="nav nav-tabs", style="border-bottom:0px;">
              <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
            </ul>
          </div>

        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Blocipedia</h1>
   <p>Wikis for the real world!</p>

 </div>

  <h3>Create Private Wikis</h3>
  <%= link_to "Sign Up for a Premium Account", new_charge_path %>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.member? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<% if user_is_authorized_to_update? %>
<h1>Edit Wiki</h1>

   <div class="row">
       <div class="col-md-4">
           <p>Wiki rules</p>
           <ul>
               <li>Don't be a jerk.</li>
               <li>Make a wiki anyone can edit!</li>
           </ul>
       </div>
       <div class="col-md-8">
           <%= form_for @wiki do |f| %>
               <div class="form-group">
                   <%= f.label :title %>
                   <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
               </div>
               <div class="form-group">
                   <%= f.label :body %>
                   <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
               </div>
               <% if user_is_authorized_to_delete? %>
                   <div class="form-group">
                       <%= f.label :private, class: 'checkbox' do %>
                           <%= f.check_box :private %> Private wiki
                       <% end %>
                   </div>
                   <div class="form-group">
                       <%= render partial: 'collaborators/form', locals: { f: f, collaborators: @wiki.collaborators } %>
                   </div>
               <% end %>
               <div class="form-group">
                   <%= f.submit "Save", class: 'btn btn-success' %>
               </div>
           <% end %>
       </div>
   </div>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
  <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %>
        </h4>
      </div>
    </div>
  <% end %>


  <div class="row">
  <div class="col-md-8">
    <p class="lead">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>They should be for the common good of all mankind.</li>
       <li>If you don't love dogs, don't post.</li>
       <li>As always, be fabulous.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
        <div class="form-group">
            <%= render partial: 'collaborators/form', locals: { f: f, collaborators: @wiki.collaborators } %>
          </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
      <% end %>
</div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
    <div class="col-md-8">
      <p><%= markdown(@wiki.body) %></p>
    </div>
    <div class="col-md-4">
          <% if user_is_authorized_to_update? %>
              <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
          <% end %>
          <%if user_is_authorized_to_delete? %>
              <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
          <% end %>
      </div>
  </div>